# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grama', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='Authority_Type',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='DOC_Fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='Doc_Sale_Ends',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='Doc_Sale_Starts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='Doc_Submit_Before',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='Due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='EMD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='Notice_Type',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='Product_Services',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='NULL', null=True),
        ),
    ]
